### PR TITLE
add: Photoview

### PR DESCRIPTION
**Pull request by berksmbl**

### CODE REVIEW

**Comment by Ponkhy** [comment]
Hey, I think the `api_cache:/app/cache` volume should be added and maybe create another user input for the photos path?

**Comment by berksmbl** [comment]
> maybe create another user input for the photos path?
I thought about it but realized it might be confusing.
Because in the first step of the installation, this path value will be requested again.
And it can have a different variant for each user.
I think it can be easily mounted via Easypanel.

image

**Review by Ponkhy — APPROVED** [review]
LGTM

**Comment by charliemoss** [comment]
Worked well. I don't know how to "review" so I just leave comments.

I had to add a BIND. Host Path: /path/to/photos  Mount Path: /photos, but you probably know that already.

**Pull request merged**
