### PR TITLE
Add Mail to Easypanel  🎉

### PR DESCRIPTION
**Pull request by Supernova3339**
This adds a mailserver, via using SMTP relay.

### CODE REVIEW

**Comment by deiucanta** [comment]
This is not a full mail server, but a mail relay server. I'm afraid people will be confused by it.

**Comment by Supernova3339** [comment]
I'll change it to `SMTP Relay`
Does that work?

**Comment by deiucanta** [comment]
I started to merge it locally but it doesn't seem to work. Port 25 should not be proxied since it's for SMTP, not HTTP.

**Comment by deiucanta** [comment]
@Supernova3339 I don't think that this is a good fit for Easypanel templates. Also, it's incomplete. Closing for now. Feel free to open again.

**Comment by Supernova3339** [comment]
hi, this is meant to be integrated with services such as plausible for SMTP
relay. It is NOT meant as an actual server!
If changed to "smtp relay", would that work better? Waiting for your reply
:)

**Pull request closed without merging**
