### PR TITLE
Add Freescout to Easypanel 🎉

### PR DESCRIPTION
**Pull request by Supernova3339**
yes

### CODE REVIEW

**Comment by miarosemathews** [comment]
[https://imgur.com/a/bjfhhzJ](url)

This results in bad gateway.

**Comment by DrMxrcy** [comment]
```
`SITE_URL=https://${input.domain},`
```

Extra "," breaks the setup, have to edit the ENV

**Comment by Supernova3339** [comment]
> ```
> `SITE_URL=https://${input.domain},`
> ```
> 
> Extra "," breaks the setup, have to edit the ENV

fixed

**Comment by DrMxrcy** [comment]
> > ```
> > `SITE_URL=https://${input.domain},`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Extra "," breaks the setup, have to edit the ENV
> 
> fixed

Perfect!

**Comment by deiucanta** [comment]
Merged locally

**Pull request closed without merging**
