### PR TITLE
Add Homarr to Easypanel 🎉

### PR DESCRIPTION
**Pull request by DrMxrcy**

### CODE REVIEW

**Comment by Supernova3339** [comment]
not possible, config file cant be written to from web UI

**Comment by deiucanta** [comment]
@DrMxrcy Thanks for your contribution!

Please remove the lock files and I will merge your PR.

**Comment by DrMxrcy** [comment]
@deiucanta Done!

**Comment by deiucanta** [comment]
I merged this PR on my machine to fix some issues with the lock files. Thanks for the contribution!

**Pull request closed without merging**
