### PR TITLE
Adding Roundcube to Easypanel and Code Prettier

### PR DESCRIPTION
**Pull request by berksmbl**

### CODE REVIEW

**Comment by Supernova3339** [comment]
Hi Berk, what is the changes for a bunch of other templates for?

**Comment by berksmbl** [comment]
> Hi Berk, what is the changes for a bunch of other templates for?

Hello, I asked this. When I used the "npm run prettier" command and automatically changed the codes to the desired format, the repos that were sent without using this command differed.

**Comment by Supernova3339** [comment]
thank you for the clarification :)

**Review by Ponkhy — APPROVED** [review]
LGTM

**Pull request merged**
