### PR TITLE
Update Lenpaste to v1.3

### PR DESCRIPTION
**Pull request by lcomrade**
Hi. I am a Lenpaste developer. Thank you for adding Lenpaste to Easypanel.

Now there is a new version of Lenpaste v1.3 ([changelog](https://git.lcomrade.su/root/lenpaste/releases/tag/v1.3)). I have updated the version of Lenpaste in Easypanel.

PS: I also added link to Easypanel in the Lenpaste README ([commit](https://git.lcomrade.su/root/lenpaste/commit/9302c38c7e27543d4e9f3dfb9d085966f5ee4337)).

### CODE REVIEW

**Comment by Supernova3339** [comment]
hiya! your software is pretty awesome, added it here :)

**Comment by Supernova3339** [comment]
if you have any reccomendations, case I'm deploying anything wrong, please feel free to let me know :)

**Comment by Supernova3339** [comment]
also, if you wanna come and chat feel free to stop by the official discord server
[https://discord.gg/9bcDSXcZQ7](https://discord.gg/9bcDSXcZQ7)

**Comment by lcomrade** [comment]
No, I don't have recommendations. Thanks for adding Lenpaste to Easypanel.

**Comment by Supernova3339** [comment]
> No, I don't have recommendations. Thanks for adding Lenpaste to Easypanel.

Sounds good :)

**Comment by deiucanta** [comment]
Hey @lcomrade - thanks for building Lenpaste and thanks for the link!

**Pull request merged**
