### PR TITLE
Add Discord to Easypanel 🎉 

### PR DESCRIPTION
**Pull request by Supernova3339**

### CODE REVIEW

**Comment by Ponkhy** [comment]
Agreed, please rename everything to WebCord, including folder, logo, etc.

**Comment by Supernova3339** [comment]
> Agreed, please rename everything to WebCord, including folder, logo, etc.

weekend here so I'll get to it next week

**Comment by deiucanta** [comment]
I agree, use WebCord so it doesn't create confusion

**Comment by Supernova3339** [comment]
> I agree, use WebCord so it doesn't create confusion

Could you recheck this, just added any needed fixes

**Comment by berksmbl** [comment]
> > I agree, use WebCord so it doesn't create confusion
> 
> Could you recheck this, just added any needed fixes

It would be better to replace the official Discord logo with [this ](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/webcord-icon.png)logo.

**Pull request merged**
