### PR TITLE
update: LimeSurvey instructions

### PR DESCRIPTION
**Pull request by berksmbl**

### CODE REVIEW

**Review by Ponkhy — APPROVED** [review]
LGTM

**Comment by Supernova3339** [comment]
tiredofit is awesome, you'll see if you deploy it yourself :)

**Comment by berksmbl** [comment]
> tiredofit is awesome, you'll see if you deploy it yourself :)
Frankly, I didn't want to use a repo that only 3 people gave stars.

**Comment by Supernova3339** [comment]
> > tiredofit is awesome, you'll see if you deploy it yourself :)
> 
> Frankly, I didn't want to use a repo that only 3 people gave stars.

stars don't really matter, it's the quality that does. tiredofit images have extensive monitoring and are typically better than the official images

**Comment by Supernova3339** [comment]
> > tiredofit is awesome, you'll see if you deploy it yourself :)
> 
> Frankly, I didn't want to use a repo that only 3 people gave stars.

please also update the image to 1.5.11

**Comment by berksmbl** [comment]
> stars don't really matter, it's the quality that does. tiredofit images have extensive monitoring and are typically better than the official images

https://i.imgur.com/AIb6UyJ.png
https://i.imgur.com/dJxuw0E.png

**Pull request closed without merging**
