### PR TITLE
Add Keila to Easypanel 🎉 

### PR DESCRIPTION
**Pull request by Supernova3339**
Docker image does NOT work!!!!!
EDIT: Docker image now works

### CODE REVIEW

**Comment by Ponkhy** [comment]
What do you exactly mean with docker image doesn't work? Just tested it on version `0.11.2` without issues.

**Comment by Supernova3339** [comment]
> What do you exactly mean with docker image doesn't work? Just tested it on version `0.11.2` without issues.

your joking
when was  the tag posted?

**Comment by Ponkhy** [comment]
> 

Roughly two months ago [pentacent/keila:0.11.2](https://hub.docker.com/layers/pentacent/keila/0.11.2/images/sha256-34aaf83a57a9b6d998c31c9f684e05165c17b0b55c6506174a01fd9c0fbe8435?context=explore)

**Review by Ponkhy — APPROVED** [review]
LGTM

**Pull request merged**
