### PR TITLE
add: OnlyOffice Document Server

### PR DESCRIPTION
**Pull request by berksmbl**

### CODE REVIEW

**Comment by berksmbl** [comment]
it already recognized the [mariadb variable](https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/run-document-server.sh#L144).

**Review by berksmbl — COMMENTED** [review]
it already recognized the [mariadb variable](https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/run-document-server.sh#L144).

**Review by Ponkhy — APPROVED** [review]
LGTM

**Comment by charliemoss** [comment]
Has any had any success linking to Nextcloud. Both are setup via EP. I have added the API. When I open a doc I get "Download failed". See screenshot.
![2023 03 28-18_54_11-screenshot-cloud charlie cx]

(https://user-images.githubusercontent.com/1388797/228326752-90ffb78c-16a3-4b88-a8a0-7b92c8b39107.png)

**Comment by berksmbl** [comment]
> Has anyone had any success linking to Nextcloud? Both are set up via EP. I have added the API. Unfortunately, when I open a doc I get "Download failed". See screenshot.

Yes, I checked it now and I was able to see the same issue on NextCloud servers installed on EP. The source of the problem seems to be NextCloud not being configured properly. Although the connection shared with OnlyOffice is HTTP, it is redirected via Traefik as HTTPS when accessed. This causes the connection to be perceived as insecure and terminated.

**Comment by Supernova3339** [comment]
have you tried filerun or owncloud? they both support onlyoffice

**Comment by berksmbl** [comment]
I am withdrawing the pull request due to proxy issues.

**Pull request closed without merging**
