### PR TITLE
Add Botpress to Easypanel 🎉 

### PR DESCRIPTION
**Pull request by Supernova3339**

### CODE REVIEW

**Comment by ivanciucdragos1** [comment]
I get "quack" message after deployment on default domain

**Comment by Supernova3339** [comment]
I'll adjust the port

**Comment by Supernova3339** [comment]
> I get "quack" message after deployment on default domain

it redirects to /admin after a few minutes

**Review by ivanciucdragos1 — APPROVED** [review]

**Comment by haraldroine** [comment]
I also get "quack!" after it being deployed. What can I do?

**Comment by ivanciucdragos1** [comment]
> 

It should redirect you after a few minutes, let me know if it doesn't work

**Comment by haraldroine** [comment]
> @haraldroine
> 
> It should redirect you after a few minutes, let me know if it doesn't work

It doesn't. I have the page open for a long time. No changes. Is there a solution to not having to wait, or is it only the first time I have to wait?

**Comment by ivanciucdragos1** [comment]
@haraldroine it's the only template you have to wait for, I'll try to find and fix the issue and keep you updated, thanks for your comment.

**Comment by haraldroine** [comment]
@ivanciucdragos1 , no worries. I opened it now, and waited 15 minutes +, no redirect to admin or anything. Stuck at "quack".

**Comment by gleert** [comment]
How was this solved? Also getting quack! after waiting 15+ minutes!

**Comment by marc-lassiter** [comment]
The issue is by default, the domain is pointing to port 80. Change it to port 4000 and you should be good to go.

**Pull request merged**
