### PR TITLE
Add evobot template

### PR DESCRIPTION
**Pull request by d8vjork**
https://github.com/eritislami/evobot

### CODE REVIEW

**Review by Ponkhy — CHANGES_REQUESTED** [review]
Would it be possible to also add a logo, maybe you can crop it from the screenshot?

**Comment by deiucanta** [comment]
@Ponkhy if this works, I will merge it without a logo

**Comment by d8vjork** [comment]
I could add quick one, sorry totally forgot to read the comment

**Comment by d8vjork** [comment]
@deiucanta @Ponkhy logo added

**Pull request merged**
