### PR TITLE
Add Cachet to Easypanel 🎉 

### PR DESCRIPTION
**Pull request by Supernova3339**
This adds Cachet to Easypanel
The image used is NOT official because the official image is broken ( shocker I know )
If this ends up unmaintained after a few years I might end up rewriting it as this is an awesome app!

### CODE REVIEW

**Review by Ponkhy — CHANGES_REQUESTED** [review]
The following needs to be added to the env:
```js
DB_DATABASE=${input.projectName}
```

**Comment by Supernova3339** [comment]
have you tried to deploy it? this is built with laravel 5

**Comment by Ponkhy** [comment]
> have you tried to deploy it? this is built with laravel 5

Yes, but of course it doesn't work unless you add the env. from my message before

**Comment by Supernova3339** [comment]
I will fix that

**Comment by deiucanta** [comment]
@Supernova3339 is this fixed?

**Comment by Supernova3339** [comment]
> @Supernova3339 is this fixed?

Fixed and working!

**Pull request merged**
